name: credit_card_type_detector
description: A package that detects credit card types based on the current credit card number patterns
version: 2.0.0-nullsafety.0
author: Tanner Davis <tannerdavisr@gmail.com>
homepage: https://github.com/cholojuanito
repository: https://github.com/cholojuanito/credit_card_type_detector
issue_tracker: https://github.com/cholojuanito/credit_card_type_detector/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.13
