name: credit_card_type_detector
description: A package that detects credit card types based on the current credit card number patterns
version: 3.0.0
homepage: https://github.com/cholojuanito
repository: https://github.com/cholojuanito/credit_card_type_detector
issue_tracker: https://github.com/cholojuanito/credit_card_type_detector/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.17.8
